In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train_set = pd.read_csv("train.csv")
test_set = pd.read_csv("test.csv")

In [3]:
train_set

,EmployeeNo,Division,Qualification,Gender,Channel_of_Recruitment,Trainings_Attended,Year_of_birth,Last_performance_score,Year_of_recruitment,Targets_met,Previous_Award,Training_score_average,State_Of_Origin,Foreign_schooled,Marital_Status,Past_Disciplinary_Action,Previous_IntraDepartmental_Movement,No_of_previous_employers,Promoted_or_Not
0,YAK/S/00001,Commercial Sales and Marketing,"MSc, MBA and PhD",Female,Direct Internal process,2,1986,12.5,2011,1,0,41,ANAMBRA,No,Married,No,No,0,0
1,YAK/S/00002,Customer Support and Field Operations,First Degree or HND,Male,Agency and others,2,1991,12.5,2015,0,0,52,ANAMBRA,Yes,Married,No,No,0,0
2,YAK/S/00003,Commercial Sales and Marketing,First Degree or HND,Male,Direct Internal process,2,1987,7.5,2012,0,0,42,KATSINA,Yes,Married,No,No,0,0
3,YAK/S/00004,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,3,1982,2.5,2009,0,0,42,NIGER,Yes,Single,No,No,1,0
4,YAK/S/00006,Information and Strategy,First Degree or HND,Male,Direct Internal process,3,1990,7.5,2012,0,0,77,AKWA IBOM,Yes,Married,No,No,1,0
5,YAK/S/00007,Customer Support and Field Operations,First Degree or HND,Female,Agency and others,2,1990,7.5,2014,0,0,51,ENUGU,Yes,Married,No,Yes,1,0
6,YAK/S/00008,Customer Support and Field Operations,"MSc, MBA and PhD",Male,Direct Internal process,2,1988,7.5,2013,0,0,55,OYO,No,Single,No,No,1,0
7,YAK/S/00009,Information and Strategy,First Degree or HND,Male,Agency and others,2,1993,10.0,2014,0,0,75,LAGOS,Yes,Married,No,No,0,0
8,YAK/S/00010,Commercial Sales and Marketing,"MSc, MBA and PhD",Male,Direct Internal process,2,1989,12.5,2014,1,0,46,ONDO,Yes,Married,No,No,0,0
9,YAK/S/00012,Commercial Sales and Marketing,First Degree or HND,Female,Direct Internal process,2,1986,12.5,2016,1,0,42,LAGOS,Yes,Married,No,No,0,1
10,YAK/S/00013,Commercial Sales and Marketing,First Degree or HND,Male,Direct Internal process,2,1972,12.5,2014,1,0,41,KWARA,Yes,Married,No,Yes,1,0
11,YAK/S/00014,Information Technology and Solution Support,"MSc, MBA and PhD",Male,Agency and others,3,1982,7.5,2003,0,0,72,EDO,Yes,Married,No,No,0,0
12,YAK/S/00018,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,2,1987,2.5,2015,0,0,43,LAGOS,Yes,Single,No,Yes,1,0
13,YAK/S/00020,Customer Support and Field Operations,First Degree or HND,Male,Agency and others,2,1984,7.5,2010,0,0,51,BAUCHI,Yes,Married,No,No,1,0
14,YAK/S/00021,Sourcing and Purchasing,First Degree or HND,Male,Agency and others,2,1986,7.5,2012,0,0,67,TARABA,Yes,Married,No,No,0,0
15,YAK/S/00022,Customer Support and Field Operations,NaN,Male,Direct Internal process,2,1980,10.0,2008,0,0,49,RIVERS,Yes,Married,No,No,1,0
16,YAK/S/00023,Business Finance Operations,First Degree or HND,Female,Agency and others,2,1993,7.5,2015,0,0,55,KADUNA,Yes,Married,No,No,4,0
17,YAK/S/00024,Sourcing and Purchasing,First Degree or HND,Male,Agency and others,2,1994,0.0,2018,0,0,62,LAGOS,Yes,Single,No,No,4,0
18,YAK/S/00025,Business Finance Operations,"MSc, MBA and PhD",Male,Direct Internal process,3,1982,12.5,2012,0,0,51,PLATEAU,Yes,Single,No,Yes,0,0
19,YAK/S/00026,Information Technology and Solution Support,First Degree or HND,Male,Agency and others,2,1994,12.5,2016,1,0,75,LAGOS,Yes,Married,No,No,1,0
20,YAK/S/00029,Information and Strategy,First Degree or HND,Male,Agency and others,2,1992,12.5,2016,1,0,72,LAGOS,Yes,Married,No,No,1,0
21,YAK/S/00030,Commercial Sales and Marketing,First Degree or HND,Male,Direct Internal process,2,1995,0.0,2018,0,0,36,EKITI,Yes,Married,No,No,1,0
22,YAK/S/00033,Commercial Sales and Marketing,NaN,Female,Direct Internal process,2,1997,2.5,2017,0,0,40,EDO,Yes,Married,No,No,1,0
23,YAK/S/00035,Information and Strategy,First Degree or HND,Male,Agency and others,3,1994,12.5,2016,1,0,79,BORNO,Yes,Married,No,No,0,0
24,YAK/S/00036,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,2,1981,5.0,2015,1,0,39,BORNO,Yes,Single,No,No,3,0
25,YAK/S/00037,Information Technology and Solution Support,First Degree or HND,Male,Direct Internal process,2,1988,10.0,2015,1,0,67,LAGOS,Yes,Married,No,No,1,0
26,YAK/S/00039,Commercial Sales and Marketing,"MSc, MBA and PhD",Male,Agency and others,2,1979,12.5,2014,1,0,43,IMO,Yes,Married,No,No,1,0
27,YAK/S/00042,Customer Support and Field Operations,First Degree or HND,Female,Agency and others,3,1998,10.0,2017,1,0,49,LAGOS,Yes,Single,No,Yes,1,0
28,YAK/S/00044,Commercial Sales and Marketing,NaN,Male,Agency and others,4,1997,5.0,2017,0,0,40,CROSS RIVER,Yes,Married,No,No,1,0
29,YAK/S/00046,Sourcing and Purchasing,First Degree or HND,Female,Direct Internal process,2,1971,12.5,2008,0,0,63,KANO,No,Married,No,Yes,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38282,YAK/S/54761,Business Finance Operations,First Degree or HND,Male,Agency and others,2,1994,5.0,2015,0,0,48,OGUN,Yes,Single,No,No,0,0
38283,YAK/S/54763,Sourcing and Purchasing,"MSc, MBA and PhD",Male,Agency and others,2,1985,5.0,2017,0,0,61,LAGOS,No,Single,No,No,0,0
38284,YAK/S/54764,Customer Support and Field Operations,First Degree or HND,Male,Direct Internal process,2,1985,12.5,2011,1,0,48,BENUE,Yes,Married,No,No,1,0
38285,YAK/S/54765,Commercial Sales and Marketing,First Degree or HND,Male,Direct Internal process,2,1975,2.5,2015,1,0,39,EDO,Yes,Single,No,No,1,0
38286,YAK/S/54766,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,3,1988,2.5,2016,0,0,40,KWARA,Yes,Married,No,No,1,0
38287,YAK/S/54769,Information Technology and Solution Support,"MSc, MBA and PhD",Female,Direct Internal process,2,1980,12.5,2013,1,0,71,BAYELSA,Yes,Single,No,No,1,0
38288,YAK/S/54770,Customer Support and Field Operations,First Degree or HND,Male,Agency and others,2,1991,2.5,2017,0,0,52,YOBE,Yes,Married,No,No,0,0
38289,YAK/S/54771,Information Technology and Solution Support,First Degree or HND,Female,Agency and others,2,1997,7.5,2017,1,0,72,KADUNA,Yes,Married,No,Yes,5,0
38290,YAK/S/54772,Commercial Sales and Marketing,First Degree or HND,Male,Direct Internal process,2,1988,12.5,2015,0,0,42,AKWA IBOM,Yes,Married,No,No,1,0
38291,YAK/S/54774,Business Finance Operations,First Degree or HND,Male,Agency and others,2,1998,0.0,2018,1,0,53,OGUN,Yes,Married,No,No,1,0
38292,YAK/S/54775,Customer Support and Field Operations,First Degree or HND,Male,Direct Internal process,2,1987,2.5,2014,0,0,49,LAGOS,Yes,Married,No,No,1,0
38293,YAK/S/54777,People/HR Management,Non-University Education,Female,Direct Internal process,2,1999,12.5,2017,0,0,39,FCT,Yes,Married,No,No,1,0
38294,YAK/S/54779,Sourcing and Purchasing,First Degree or HND,Female,Direct Internal process,2,1991,7.5,2016,0,0,62,FCT,Yes,Married,No,No,0,0
38295,YAK/S/54781,Customer Support and Field Operations,First Degree or HND,Female,Direct Internal process,2,1982,12.5,2012,0,0,52,RIVERS,Yes,Married,No,No,1,0
38296,YAK/S/54783,Customer Support and Field Operations,Non-University Education,Male,Direct Internal process,3,1995,7.5,2017,0,0,52,RIVERS,Yes,Married,No,Yes,0,0
38297,YAK/S/54786,Information Technology and Solution Support,First Degree or HND,Male,Agency and others,2,1988,10.0,2012,1,0,69,DELTA,Yes,Single,No,No,1,0
38298,YAK/S/54788,Information Technology and Solution Support,First Degree or HND,Male,Direct Internal process,5,1995,7.5,2016,0,0,76,FCT,Yes,Married,No,No,0,0
38299,YAK/S/54789,Commercial Sales and Marketing,First Degree or HND,Female,Direct Internal process,3,1993,7.5,2016,0,0,40,FCT,Yes,Married,No,No,0,0
38300,YAK/S/54790,Commercial Sales and Marketing,"MSc, MBA and PhD",Male,Agency and others,4,1990,7.5,2010,0,0,42,OYO,Yes,Single,No,No,1,0
38301,YAK/S/54791,People/HR Management,First Degree or HND,Female,Direct Internal process,2,1973,12.5,2015,0,0,41,DELTA,Yes,Single,No,No,2,0
38302,YAK/S/54793,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,2,1962,7.5,2008,0,0,57,KANO,Yes,Married,No,No,1,1
38303,YAK/S/54794,Information Technology and Solution Support,First Degree or HND,Male,Agency and others,2,1988,2.5,2010,0,0,71,BENUE,Yes,Single,No,No,1,0
38304,YAK/S/54796,Sourcing and Purchasing,"MSc, MBA and PhD",Male,Agency and others,2,1986,7.5,2012,0,0,62,FCT,Yes,Married,No,Yes,4,0
38305,YAK/S/54799,Commercial Sales and Marketing,"MSc, MBA and PhD",Female,Agency and others,3,1981,12.5,2015,1,0,43,FCT,Yes,Married,No,No,1,0
38306,YAK/S/54801,People/HR Management,First Degree or HND,Male,Agency and others,3,1987,12.5,2016,0,0,44,LAGOS,Yes,Married,No,No,1,0
38307,YAK/S/54802,Information Technology and Solution Support,First Degree or HND,Female,Direct Internal process,2,1990,0.0,2018,0,0,70,LAGOS,Yes,Married,No,No,0,0
38308,YAK/S/54805,Customer Support and Field Operations,"MSc, MBA and PhD",Female,Agency and others,2,1984,5.0,2013,0,0,48,IMO,Yes,Married,No,No,1,0
38309,YAK/S/54806,Information and Strategy,First Degree or HND,Male,Agency and others,2,1994,12.5,2016,1,0,71,ANAMBRA,No,Married,No,No,3,0
38310,YAK/S/54807,Commercial Sales and Marketing,NaN,Male,Direct Internal process,2,1992,2.5,2017,0,0,37,KWARA,Yes,Married,No,No,1,0
38311,YAK/S/54808,People/HR Management,First Degree or HND,Male,Agency and others,2,1994,2.5,2014,0,0,41,KWARA,Yes,Single,No,No,2,0

In [4]:
test_set

,EmployeeNo,Division,Qualification,Gender,Channel_of_Recruitment,Trainings_Attended,Year_of_birth,Last_performance_score,Year_of_recruitment,Targets_met,Previous_Award,Training_score_average,State_Of_Origin,Foreign_schooled,Marital_Status,Past_Disciplinary_Action,Previous_IntraDepartmental_Movement,No_of_previous_employers
0,YAK/S/00005,Information Technology and Solution Support,First Degree or HND,Male,Agency and others,2,1976,7.5,2017,0,0,65,FCT,Yes,Married,No,No,1
1,YAK/S/00011,Information Technology and Solution Support,NaN,Male,Direct Internal process,2,1991,0.0,2018,0,0,69,OGUN,Yes,Married,No,No,1
2,YAK/S/00015,Research and Innovation,"MSc, MBA and PhD",Male,Direct Internal process,2,1984,7.5,2012,0,0,76,KANO,Yes,Married,No,No,1
3,YAK/S/00016,Customer Support and Field Operations,First Degree or HND,Male,Agency and others,2,1984,2.5,2009,0,0,52,RIVERS,No,Single,No,No,1
4,YAK/S/00017,Information Technology and Solution Support,First Degree or HND,Male,Agency and others,2,1983,7.5,2014,1,0,69,FCT,Yes,Married,No,No,0
5,YAK/S/00019,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,2,1987,12.5,2011,1,0,38,BENUE,Yes,Married,No,No,1
6,YAK/S/00027,Sourcing and Purchasing,First Degree or HND,Male,Agency and others,2,1990,12.5,2015,1,0,60,FCT,Yes,Married,No,No,1
7,YAK/S/00028,Information Technology and Solution Support,First Degree or HND,Male,Agency and others,2,1988,10.0,2015,0,0,71,FCT,Yes,Married,No,No,1
8,YAK/S/00031,Sourcing and Purchasing,First Degree or HND,Male,Direct Internal process,2,1984,12.5,2009,1,0,64,LAGOS,Yes,Married,No,No,1
9,YAK/S/00032,Business Finance Operations,First Degree or HND,Male,Agency and others,3,1995,2.5,2017,0,0,53,RIVERS,Yes,Married,No,Yes,1
10,YAK/S/00034,Customer Support and Field Operations,First Degree or HND,Male,Direct Internal process,3,1964,10.0,2013,0,0,50,LAGOS,Yes,Married,No,Yes,0
11,YAK/S/00038,Commercial Sales and Marketing,First Degree or HND,Female,Direct Internal process,2,1981,12.5,2016,0,0,39,FCT,Yes,Single,No,No,1
12,YAK/S/00040,Commercial Sales and Marketing,First Degree or HND,Male,Direct Internal process,2,1988,12.5,2013,1,0,43,OYO,Yes,Married,No,No,1
13,YAK/S/00041,Information Technology and Solution Support,First Degree or HND,Male,Agency and others,2,1987,7.5,2009,0,0,72,KANO,Yes,Single,No,No,1
14,YAK/S/00043,People/HR Management,First Degree or HND,Male,Direct Internal process,2,1962,10.0,1993,1,0,44,RIVERS,Yes,Married,No,No,1
15,YAK/S/00045,Information and Strategy,First Degree or HND,Male,Agency and others,2,1977,12.5,2007,0,0,80,BORNO,Yes,Single,No,No,1
16,YAK/S/00047,Sourcing and Purchasing,"MSc, MBA and PhD",Female,Agency and others,2,1984,10.0,2015,0,0,63,KATSINA,Yes,Married,No,No,1
17,YAK/S/00049,Commercial Sales and Marketing,First Degree or HND,Male,Direct Internal process,2,1991,7.5,2016,1,0,41,KANO,Yes,Married,No,No,2
18,YAK/S/00050,Sourcing and Purchasing,"MSc, MBA and PhD",Female,Direct Internal process,2,1965,7.5,2007,0,0,65,FCT,Yes,Married,No,No,0
19,YAK/S/00051,Business Finance Operations,First Degree or HND,Male,Direct Internal process,2,2001,10.0,2017,1,0,52,CROSS RIVER,No,Married,No,No,0
20,YAK/S/00058,Research and Innovation,"MSc, MBA and PhD",Male,Direct Internal process,2,1981,7.5,2014,1,0,76,OGUN,Yes,Married,No,No,1
21,YAK/S/00060,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,2,1981,10.0,2012,0,0,44,KADUNA,Yes,Married,No,Yes,1
22,YAK/S/00063,Information and Strategy,First Degree or HND,Female,Agency and others,2,1993,0.0,2018,1,0,72,OYO,Yes,Married,No,No,0
23,YAK/S/00067,Business Finance Operations,First Degree or HND,Male,Agency and others,2,1994,0.0,2018,1,1,50,DELTA,Yes,Married,No,No,2
24,YAK/S/00069,Sourcing and Purchasing,First Degree or HND,Male,Agency and others,2,1991,10.0,2013,1,0,67,FCT,Yes,Married,No,No,1
25,YAK/S/00072,Information Technology and Solution Support,"MSc, MBA and PhD",Male,Agency and others,2,1987,12.5,2012,1,0,70,LAGOS,Yes,Married,No,Yes,0
26,YAK/S/00080,Commercial Sales and Marketing,First Degree or HND,Male,Direct Internal process,2,1991,7.5,2016,0,0,50,IMO,Yes,Married,No,No,0
27,YAK/S/00083,Commercial Sales and Marketing,NaN,Male,Direct Internal process,3,1996,7.5,2017,0,0,45,FCT,Yes,Married,No,No,1
28,YAK/S/00084,Research and Innovation,First Degree or HND,Male,Agency and others,2,1985,10.0,2011,0,0,74,IMO,Yes,Married,No,No,1
29,YAK/S/00088,Commercial Sales and Marketing,NaN,Male,Direct Internal process,2,1982,2.5,2010,0,0,41,ONDO,Yes,Married,No,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16466,YAK/S/54726,Business Finance Operations,First Degree or HND,Female,Agency and others,2,1990,7.5,2011,0,0,51,KADUNA,Yes,Married,No,Yes,1
16467,YAK/S/54738,Sourcing and Purchasing,First Degree or HND,Male,Agency and others,2,1990,7.5,2012,0,0,58,CROSS RIVER,Yes,Married,No,No,0
16468,YAK/S/54742,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,2,1990,12.5,2014,1,0,45,KANO,Yes,Married,No,Yes,0
16469,YAK/S/54743,Commercial Sales and Marketing,NaN,Male,Agency and others,2,1993,10.0,2016,0,0,39,ENUGU,Yes,Single,No,No,1
16470,YAK/S/54744,Information Technology and Solution Support,First Degree or HND,Male,Direct Internal process,3,1985,10.0,2016,0,0,73,KWARA,Yes,Single,No,No,0
16471,YAK/S/54748,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,2,1986,5.0,2011,0,0,42,BAUCHI,Yes,Married,No,No,1
16472,YAK/S/54752,Information Technology and Solution Support,"MSc, MBA and PhD",Female,Agency and others,2,1980,2.5,2009,0,0,72,LAGOS,Yes,Married,No,No,0
16473,YAK/S/54754,Customer Support and Field Operations,First Degree or HND,Female,Direct Internal process,2,1996,12.5,2017,1,0,51,JIGAWA,Yes,Married,No,No,2
16474,YAK/S/54755,Information Technology and Solution Support,First Degree or HND,Female,Agency and others,2,1979,7.5,2005,0,0,71,KWARA,Yes,Married,No,No,1
16475,YAK/S/54757,Customer Support and Field Operations,First Degree or HND,Female,Direct Internal process,2,1986,12.5,2015,0,0,55,SOKOTO,Yes,Married,No,No,1
16476,YAK/S/54758,Information Technology and Solution Support,"MSc, MBA and PhD",Male,Agency and others,2,1967,10.0,2012,0,0,73,KANO,No,Married,No,No,0
16477,YAK/S/54760,Commercial Sales and Marketing,"MSc, MBA and PhD",Male,Agency and others,4,1986,2.5,2009,0,0,43,DELTA,Yes,Married,No,No,3
16478,YAK/S/54762,Sourcing and Purchasing,First Degree or HND,Female,Direct Internal process,2,1991,10.0,2017,1,0,78,ABIA,Yes,Married,No,No,1
16479,YAK/S/54767,Customer Support and Field Operations,First Degree or HND,Male,Direct Internal process,2,1984,7.5,2016,1,0,47,RIVERS,Yes,Married,No,Yes,0
16480,YAK/S/54768,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,2,1972,10.0,2014,0,0,39,LAGOS,Yes,Married,No,No,1
16481,YAK/S/54773,Customer Support and Field Operations,"MSc, MBA and PhD",Male,Agency and others,2,1984,12.5,2017,1,1,49,EDO,Yes,Single,No,No,1
16482,YAK/S/54776,Customer Support and Field Operations,First Degree or HND,Male,Agency and others,2,1991,2.5,2015,0,0,52,KWARA,Yes,Married,No,No,0
16483,YAK/S/54778,Information Technology and Solution Support,First Degree or HND,Male,Agency and others,2,1969,5.0,2016,0,0,69,LAGOS,Yes,Single,No,No,0
16484,YAK/S/54780,Information Technology and Solution Support,First Degree or HND,Female,Direct Internal process,2,1987,7.5,2016,0,0,78,DELTA,Yes,Married,No,No,5
16485,YAK/S/54782,People/HR Management,First Degree or HND,Female,Direct Internal process,2,1983,12.5,2016,1,0,42,KEBBI,No,Single,No,No,4
16486,YAK/S/54784,Sourcing and Purchasing,Non-University Education,Male,Agency and others,4,1998,7.5,2017,0,0,63,OGUN,Yes,Married,No,No,0
16487,YAK/S/54785,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,2,1982,12.5,2010,0,0,40,LAGOS,Yes,Married,No,No,0
16488,YAK/S/54787,Commercial Sales and Marketing,First Degree or HND,Female,Direct Internal process,3,1990,2.5,2015,0,0,43,FCT,Yes,Single,No,No,2
16489,YAK/S/54792,Information Technology and Solution Support,First Degree or HND,Male,Direct Internal process,2,1989,2.5,2016,1,0,74,PLATEAU,Yes,Married,No,No,1
16490,YAK/S/54795,Customer Support and Field Operations,First Degree or HND,Male,Agency and others,2,1984,10.0,2012,1,0,46,LAGOS,Yes,Married,No,Yes,1
16491,YAK/S/54797,Commercial Sales and Marketing,"MSc, MBA and PhD",Male,Agency and others,2,1987,7.5,2012,0,0,52,PLATEAU,Yes,Married,No,No,1
16492,YAK/S/54798,Commercial Sales and Marketing,First Degree or HND,Male,Direct Internal process,2,1993,12.5,2016,1,1,39,OGUN,Yes,Single,No,No,0
16493,YAK/S/54800,Sourcing and Purchasing,"MSc, MBA and PhD",Female,Agency and others,2,1971,12.5,2013,1,1,59,NASSARAWA,Yes,Married,No,No,0
16494,YAK/S/54803,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,3,1990,2.5,2017,0,0,41,OGUN,Yes,Married,No,No,3
16495,YAK/S/54804,Information Technology and Solution Support,First Degree or HND,Male,Direct Internal process,2,1973,7.5,2002,0,0,70,ANAMBRA,Yes,Married,No,No,1

In [5]:
train_set  = train_set.drop(['EmployeeNo','Division','Gender','Year_of_birth','State_Of_Origin'], axis=1)
test_set  = test_set.drop(['EmployeeNo','Division','Gender','Year_of_birth','State_Of_Origin'], axis=1)

In [6]:
train_set

,Qualification,Channel_of_Recruitment,Trainings_Attended,Last_performance_score,Year_of_recruitment,Targets_met,Previous_Award,Training_score_average,Foreign_schooled,Marital_Status,Past_Disciplinary_Action,Previous_IntraDepartmental_Movement,No_of_previous_employers,Promoted_or_Not
0,"MSc, MBA and PhD",Direct Internal process,2,12.5,2011,1,0,41,No,Married,No,No,0,0
1,First Degree or HND,Agency and others,2,12.5,2015,0,0,52,Yes,Married,No,No,0,0
2,First Degree or HND,Direct Internal process,2,7.5,2012,0,0,42,Yes,Married,No,No,0,0
3,First Degree or HND,Agency and others,3,2.5,2009,0,0,42,Yes,Single,No,No,1,0
4,First Degree or HND,Direct Internal process,3,7.5,2012,0,0,77,Yes,Married,No,No,1,0
5,First Degree or HND,Agency and others,2,7.5,2014,0,0,51,Yes,Married,No,Yes,1,0
6,"MSc, MBA and PhD",Direct Internal process,2,7.5,2013,0,0,55,No,Single,No,No,1,0
7,First Degree or HND,Agency and others,2,10.0,2014,0,0,75,Yes,Married,No,No,0,0
8,"MSc, MBA and PhD",Direct Internal process,2,12.5,2014,1,0,46,Yes,Married,No,No,0,0
9,First Degree or HND,Direct Internal process,2,12.5,2016,1,0,42,Yes,Married,No,No,0,1
10,First Degree or HND,Direct Internal process,2,12.5,2014,1,0,41,Yes,Married,No,Yes,1,0
11,"MSc, MBA and PhD",Agency and others,3,7.5,2003,0,0,72,Yes,Married,No,No,0,0
12,First Degree or HND,Agency and others,2,2.5,2015,0,0,43,Yes,Single,No,Yes,1,0
13,First Degree or HND,Agency and others,2,7.5,2010,0,0,51,Yes,Married,No,No,1,0
14,First Degree or HND,Agency and others,2,7.5,2012,0,0,67,Yes,Married,No,No,0,0
15,NaN,Direct Internal process,2,10.0,2008,0,0,49,Yes,Married,No,No,1,0
16,First Degree or HND,Agency and others,2,7.5,2015,0,0,55,Yes,Married,No,No,4,0
17,First Degree or HND,Agency and others,2,0.0,2018,0,0,62,Yes,Single,No,No,4,0
18,"MSc, MBA and PhD",Direct Internal process,3,12.5,2012,0,0,51,Yes,Single,No,Yes,0,0
19,First Degree or HND,Agency and others,2,12.5,2016,1,0,75,Yes,Married,No,No,1,0
20,First Degree or HND,Agency and others,2,12.5,2016,1,0,72,Yes,Married,No,No,1,0
21,First Degree or HND,Direct Internal process,2,0.0,2018,0,0,36,Yes,Married,No,No,1,0
22,NaN,Direct Internal process,2,2.5,2017,0,0,40,Yes,Married,No,No,1,0
23,First Degree or HND,Agency and others,3,12.5,2016,1,0,79,Yes,Married,No,No,0,0
24,First Degree or HND,Agency and others,2,5.0,2015,1,0,39,Yes,Single,No,No,3,0
25,First Degree or HND,Direct Internal process,2,10.0,2015,1,0,67,Yes,Married,No,No,1,0
26,"MSc, MBA and PhD",Agency and others,2,12.5,2014,1,0,43,Yes,Married,No,No,1,0
27,First Degree or HND,Agency and others,3,10.0,2017,1,0,49,Yes,Single,No,Yes,1,0
28,NaN,Agency and others,4,5.0,2017,0,0,40,Yes,Married,No,No,1,0
29,First Degree or HND,Direct Internal process,2,12.5,2008,0,0,63,No,Married,No,Yes,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38282,First Degree or HND,Agency and others,2,5.0,2015,0,0,48,Yes,Single,No,No,0,0
38283,"MSc, MBA and PhD",Agency and others,2,5.0,2017,0,0,61,No,Single,No,No,0,0
38284,First Degree or HND,Direct Internal process,2,12.5,2011,1,0,48,Yes,Married,No,No,1,0
38285,First Degree or HND,Direct Internal process,2,2.5,2015,1,0,39,Yes,Single,No,No,1,0
38286,First Degree or HND,Agency and others,3,2.5,2016,0,0,40,Yes,Married,No,No,1,0
38287,"MSc, MBA and PhD",Direct Internal process,2,12.5,2013,1,0,71,Yes,Single,No,No,1,0
38288,First Degree or HND,Agency and others,2,2.5,2017,0,0,52,Yes,Married,No,No,0,0
38289,First Degree or HND,Agency and others,2,7.5,2017,1,0,72,Yes,Married,No,Yes,5,0
38290,First Degree or HND,Direct Internal process,2,12.5,2015,0,0,42,Yes,Married,No,No,1,0
38291,First Degree or HND,Agency and others,2,0.0,2018,1,0,53,Yes,Married,No,No,1,0
38292,First Degree or HND,Direct Internal process,2,2.5,2014,0,0,49,Yes,Married,No,No,1,0
38293,Non-University Education,Direct Internal process,2,12.5,2017,0,0,39,Yes,Married,No,No,1,0
38294,First Degree or HND,Direct Internal process,2,7.5,2016,0,0,62,Yes,Married,No,No,0,0
38295,First Degree or HND,Direct Internal process,2,12.5,2012,0,0,52,Yes,Married,No,No,1,0
38296,Non-University Education,Direct Internal process,3,7.5,2017,0,0,52,Yes,Married,No,Yes,0,0
38297,First Degree or HND,Agency and others,2,10.0,2012,1,0,69,Yes,Single,No,No,1,0
38298,First Degree or HND,Direct Internal process,5,7.5,2016,0,0,76,Yes,Married,No,No,0,0
38299,First Degree or HND,Direct Internal process,3,7.5,2016,0,0,40,Yes,Married,No,No,0,0
38300,"MSc, MBA and PhD",Agency and others,4,7.5,2010,0,0,42,Yes,Single,No,No,1,0
38301,First Degree or HND,Direct Internal process,2,12.5,2015,0,0,41,Yes,Single,No,No,2,0
38302,First Degree or HND,Agency and others,2,7.5,2008,0,0,57,Yes,Married,No,No,1,1
38303,First Degree or HND,Agency and others,2,2.5,2010,0,0,71,Yes,Single,No,No,1,0
38304,"MSc, MBA and PhD",Agency and others,2,7.5,2012,0,0,62,Yes,Married,No,Yes,4,0
38305,"MSc, MBA and PhD",Agency and others,3,12.5,2015,1,0,43,Yes,Married,No,No,1,0
38306,First Degree or HND,Agency and others,3,12.5,2016,0,0,44,Yes,Married,No,No,1,0
38307,First Degree or HND,Direct Internal process,2,0.0,2018,0,0,70,Yes,Married,No,No,0,0
38308,"MSc, MBA and PhD",Agency and others,2,5.0,2013,0,0,48,Yes,Married,No,No,1,0
38309,First Degree or HND,Agency and others,2,12.5,2016,1,0,71,No,Married,No,No,3,0
38310,NaN,Direct Internal process,2,2.5,2017,0,0,37,Yes,Married,No,No,1,0
38311,First Degree or HND,Agency and others,2,2.5,2014,0,0,41,Yes,Single,No,No,2,0

In [7]:
#  taking care of categorical data
train_set.isnull().sum()

Qualification                          1679
Channel_of_Recruitment                    0
Trainings_Attended                        0
Last_performance_score                    0
Year_of_recruitment                       0
Targets_met                               0
Previous_Award                            0
Training_score_average                    0
Foreign_schooled                          0
Marital_Status                            0
Past_Disciplinary_Action                  0
Previous_IntraDepartmental_Movement       0
No_of_previous_employers                  0
Promoted_or_Not                           0
dtype: int64

In [8]:
test_set.isnull().sum()

Qualification                          730
Channel_of_Recruitment                   0
Trainings_Attended                       0
Last_performance_score                   0
Year_of_recruitment                      0
Targets_met                              0
Previous_Award                           0
Training_score_average                   0
Foreign_schooled                         0
Marital_Status                           0
Past_Disciplinary_Action                 0
Previous_IntraDepartmental_Movement      0
No_of_previous_employers                 0
dtype: int64

In [9]:
train_set['Qualification'] = train_set['Qualification'].fillna("First Degree or HND")
test_set['Qualification'] = train_set['Qualification'].fillna("First Degree or HND")

# Fixing the more than 5 value in the 'No_of_previous_employers' column
train_set['No_of_previous_employers'] = train_set['No_of_previous_employers'].replace('More than 5',8)

test_set['No_of_previous_employers'] = test_set['No_of_previous_employers'].replace('More than 5',8)

In [10]:
train_set.isnull().sum()

Qualification                          0
Channel_of_Recruitment                 0
Trainings_Attended                     0
Last_performance_score                 0
Year_of_recruitment                    0
Targets_met                            0
Previous_Award                         0
Training_score_average                 0
Foreign_schooled                       0
Marital_Status                         0
Past_Disciplinary_Action               0
Previous_IntraDepartmental_Movement    0
No_of_previous_employers               0
Promoted_or_Not                        0
dtype: int64

In [11]:
test_set.isnull().sum()

Qualification                          0
Channel_of_Recruitment                 0
Trainings_Attended                     0
Last_performance_score                 0
Year_of_recruitment                    0
Targets_met                            0
Previous_Award                         0
Training_score_average                 0
Foreign_schooled                       0
Marital_Status                         0
Past_Disciplinary_Action               0
Previous_IntraDepartmental_Movement    0
No_of_previous_employers               0
dtype: int64

In [12]:
x = train_set.iloc[:,0:-1].values
y = train_set.iloc[:,-1].values

test = test_set.iloc[:, 0:].values

In [13]:
 pd.DataFrame(test)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,"MSc, MBA and PhD",Agency and others,2,7.5,2017,0,0,65,Yes,Married,No,No,1
1,First Degree or HND,Direct Internal process,2,0,2018,0,0,69,Yes,Married,No,No,1
2,First Degree or HND,Direct Internal process,2,7.5,2012,0,0,76,Yes,Married,No,No,1
3,First Degree or HND,Agency and others,2,2.5,2009,0,0,52,No,Single,No,No,1
4,First Degree or HND,Agency and others,2,7.5,2014,1,0,69,Yes,Married,No,No,0
5,First Degree or HND,Agency and others,2,12.5,2011,1,0,38,Yes,Married,No,No,1
6,"MSc, MBA and PhD",Agency and others,2,12.5,2015,1,0,60,Yes,Married,No,No,1
7,First Degree or HND,Agency and others,2,10,2015,0,0,71,Yes,Married,No,No,1
8,"MSc, MBA and PhD",Direct Internal process,2,12.5,2009,1,0,64,Yes,Married,No,No,1
9,First Degree or HND,Agency and others,3,2.5,2017,0,0,53,Yes,Married,No,Yes,1
10,First Degree or HND,Direct Internal process,3,10,2013,0,0,50,Yes,Married,No,Yes,0
11,"MSc, MBA and PhD",Direct Internal process,2,12.5,2016,0,0,39,Yes,Single,No,No,1
12,First Degree or HND,Direct Internal process,2,12.5,2013,1,0,43,Yes,Married,No,No,1
13,First Degree or HND,Agency and others,2,7.5,2009,0,0,72,Yes,Single,No,No,1
14,First Degree or HND,Direct Internal process,2,10,1993,1,0,44,Yes,Married,No,No,1
15,First Degree or HND,Agency and others,2,12.5,2007,0,0,80,Yes,Single,No,No,1
16,First Degree or HND,Agency and others,2,10,2015,0,0,63,Yes,Married,No,No,1
17,First Degree or HND,Direct Internal process,2,7.5,2016,1,0,41,Yes,Married,No,No,2
18,"MSc, MBA and PhD",Direct Internal process,2,7.5,2007,0,0,65,Yes,Married,No,No,0
19,First Degree or HND,Direct Internal process,2,10,2017,1,0,52,No,Married,No,No,0
20,First Degree or HND,Direct Internal process,2,7.5,2014,1,0,76,Yes,Married,No,No,1
21,First Degree or HND,Agency and others,2,10,2012,0,0,44,Yes,Married,No,Yes,1
22,First Degree or HND,Agency and others,2,0,2018,1,0,72,Yes,Married,No,No,0
23,First Degree or HND,Agency and others,2,0,2018,1,1,50,Yes,Married,No,No,2
24,First Degree or HND,Agency and others,2,10,2013,1,0,67,Yes,Married,No,No,1
25,First Degree or HND,Agency and others,2,12.5,2012,1,0,70,Yes,Married,No,Yes,0
26,"MSc, MBA and PhD",Direct Internal process,2,7.5,2016,0,0,50,Yes,Married,No,No,0
27,First Degree or HND,Direct Internal process,3,7.5,2017,0,0,45,Yes,Married,No,No,1
28,First Degree or HND,Agency and others,2,10,2011,0,0,74,Yes,Married,No,No,1
29,First Degree or HND,Direct Internal process,2,2.5,2010,0,0,41,Yes,Married,No,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16466,First Degree or HND,Agency and others,2,7.5,2011,0,0,51,Yes,Married,No,Yes,1
16467,"MSc, MBA and PhD",Agency and others,2,7.5,2012,0,0,58,Yes,Married,No,No,0
16468,"MSc, MBA and PhD",Agency and others,2,12.5,2014,1,0,45,Yes,Married,No,Yes,0
16469,"MSc, MBA and PhD",Agency and others,2,10,2016,0,0,39,Yes,Single,No,No,1
16470,First Degree or HND,Direct Internal process,3,10,2016,0,0,73,Yes,Single,No,No,0
16471,First Degree or HND,Agency and others,2,5,2011,0,0,42,Yes,Married,No,No,1
16472,"MSc, MBA and PhD",Agency and others,2,2.5,2009,0,0,72,Yes,Married,No,No,0
16473,"MSc, MBA and PhD",Direct Internal process,2,12.5,2017,1,0,51,Yes,Married,No,No,2
16474,First Degree or HND,Agency and others,2,7.5,2005,0,0,71,Yes,Married,No,No,1
16475,First Degree or HND,Direct Internal process,2,12.5,2015,0,0,55,Yes,Married,No,No,1
16476,First Degree or HND,Agency and others,2,10,2012,0,0,73,No,Married,No,No,0
16477,First Degree or HND,Agency and others,4,2.5,2009,0,0,43,Yes,Married,No,No,3
16478,First Degree or HND,Direct Internal process,2,10,2017,1,0,78,Yes,Married,No,No,1
16479,First Degree or HND,Direct Internal process,2,7.5,2016,1,0,47,Yes,Married,No,Yes,0
16480,"MSc, MBA and PhD",Agency and others,2,10,2014,0,0,39,Yes,Married,No,No,1
16481,"MSc, MBA and PhD",Agency and others,2,12.5,2017,1,1,49,Yes,Single,No,No,1
16482,First Degree or HND,Agency and others,2,2.5,2015,0,0,52,Yes,Married,No,No,0
16483,First Degree or HND,Agency and others,2,5,2016,0,0,69,Yes,Single,No,No,0
16484,First Degree or HND,Direct Internal process,2,7.5,2016,0,0,78,Yes,Married,No,No,5
16485,First Degree or HND,Direct Internal process,2,12.5,2016,1,0,42,No,Single,No,No,4
16486,First Degree or HND,Agency and others,4,7.5,2017,0,0,63,Yes,Married,No,No,0
16487,First Degree or HND,Agency and others,2,12.5,2010,0,0,40,Yes,Married,No,No,0
16488,First Degree or HND,Direct Internal process,3,2.5,2015,0,0,43,Yes,Single,No,No,2
16489,First Degree or HND,Direct Internal process,2,2.5,2016,1,0,74,Yes,Married,No,No,1
16490,First Degree or HND,Agency and others,2,10,2012,1,0,46,Yes,Married,No,Yes,1
16491,First Degree or HND,Agency and others,2,7.5,2012,0,0,52,Yes,Married,No,No,1
16492,First Degree or HND,Direct Internal process,2,12.5,2016,1,1,39,Yes,Single,No,No,0
16493,First Degree or HND,Agency and others,2,12.5,2013,1,1,59,Yes,Married,No,No,0
16494,First Degree or HND,Agency and others,3,2.5,2017,0,0,41,Yes,Married,No,No,3
16495,First Degree or HND,Direct Internal process,2,7.5,2002,0,0,70,Yes,Married,No,No,1

In [14]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_x = LabelEncoder()
x[:,0] = labelencoder_x.fit_transform(x[:,0])
x[:,1] = labelencoder_x.fit_transform(x[:,1])
x[:,8] = labelencoder_x.fit_transform(x[:,8])
x[:,9] = labelencoder_x.fit_transform(x[:,9])
x[:,10] = labelencoder_x.fit_transform(x[:,10])
x[:,11] = labelencoder_x.fit_transform(x[:,11])
x[:,12] = labelencoder_x.fit_transform(x[:,12])

onehotencoder1 = OneHotEncoder(categorical_features = [[1],[8],[9]])
x = onehotencoder1.fit_transform(x).toarray()

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_2 = LabelEncoder()
test[:,0] = labelencoder_2.fit_transform(test[:,0])
test[:,1] = labelencoder_2.fit_transform(test[:,1])
test[:,8] = labelencoder_2.fit_transform(test[:,8])
test[:,9] = labelencoder_2.fit_transform(test[:,9])
test[:,10] = labelencoder_2.fit_transform(test[:,10])
test[:,11] = labelencoder_2.fit_transform(test[:,11])
test[:,12] = labelencoder_x.fit_transform(test[:,12])

onehotencoder1 = OneHotEncoder(categorical_features = [[1],[8],[9]])
test = onehotencoder1.fit_transform(test).toarray()

C:\Users\Dynamo\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Dynamo\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)
C:\Users\Dynamo\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Dynamo\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

In [15]:
x

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 3.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 2.]])

In [16]:
#avoiding dummy variable trap
x = x[:, 1:]
test = test[:,1:]

In [17]:
#splitting the dataset into train and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.1, random_state= 0)

In [18]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)

test = sc_x.fit_transform(test)

In [19]:

# Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

regressor = LogisticRegression()
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)
acc_regressor = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_regressor)

C:\Users\Dynamo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

8.19

In [ ]:



# Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
randomforest = RandomForestClassifier()
randomforest.fit(x_train, y_train)
y_pred = randomforest.predict(x_test)
acc_randomforest = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_randomforest)

In [21]:
#Applying k-fold cross validation
from sklearn.model_selection import cross_val_score
accu = cross_val_score(estimator = gaussian, X = x_train,y = y_train, cv = 10 )
print (accu.mean())
print (accu.std())

0.8879933133559209
0.004827322711136489

In [ ]:
y_pred

In [ ]:
new_pred = randomforest.predict(test)
new_pred

In [ ]:
test_sets = pd.read_csv("test.csv")

In [ ]:
submision1 = pd.DataFrame({"EmployeeNo": test_sets["EmployeeNo"], "Promoted_or_Not": new_pred})
submision1

In [ ]:
submision1 = submision1.to_csv("submision2.csv", index = False)

In [20]:

# Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

gaussian = GaussianNB()
gaussian.fit(x_train, y_train)
y_pred = gaussian.predict(x_test)
acc_gaussian = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_gaussian)

91.83

In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
decisiontree = DecisionTreeClassifier()
decisiontree.fit(x_train, y_train)
y_pred = decisiontree.predict(x_test)
acc_decisiontree = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_decisiontree)

In [ ]:
# KNN or k-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
acc_knn = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_knn)

In [ ]:
# Gradient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
gbk = GradientBoostingClassifier()
gbk.fit(x_train, y_train)
y_pred = gbk.predict(x_test)
acc_gbk = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_gbk)

In [ ]:
# Linear SVC
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
linear_svc = LinearSVC()
linear_svc.fit(x_train, y_train)
y_pred = linear_svc.predict(x_test)
acc_linear_svc = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_linear_svc)

In [ ]:
# Stochastic Gradient Descent
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
sgd = SGDClassifier()
sgd.fit(x_train, y_train)
y_pred = sgd.predict(x_test)
acc_sgd = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_sgd)

In [ ]:
# Perceptron
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
perceptron = Perceptron()
perceptron.fit(x_train, y_train)
y_pred = perceptron.predict(x_test)
acc_perceptron = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_perceptron)